#!/bin/bash
#SBATCH --job-name=align_BRD4input 	# Job name
#SBATCH --mail-type=END,FAIL             # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=jps558@york.ac.uk    # Where to send mail  
#SBATCH --ntasks=1                       # Run on a single CPU
#SBATCH --mem=30gb                       # Job memory request
#SBATCH --time=03:30:00                  # Time limit hrs:min:sec
#SBATCH --output=basic_job_%j.log        # Standard output and error log
#SBATCH --account=biol-hic-2020          # Project account
#SBATCH --partition=preempt

module purge
module load bio/deepTools/3.5.1-foss-2021b
module load bio/BWA/0.7.17-foss-2019b
module load bio/SAMtools/1.9-foss-2018b
module load bio/BEDTools/2.30.0-GCC-11.2.0
cd /mnt/lustre/groups/biol-hic-2020/jack/workingChipdata/HCT116_Brd4/input
bwa mem -p -t 40 /mnt/lustre/groups/biol-hic-2020/jack/staging/hg38/hg38.fa SRR2481800.fastq > SRR2481800_aligned.sam
cd /mnt/lustre/groups/biol-hic-2020/jack/workingCCdata/HCT-116_WT_HyPB_PB_+-SP1