#!/bin/bash
#SBATCH --job-name=filt_SP1_MACS2	 # Job name
#SBATCH --mail-type=END,FAIL             # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=jps558@york.ac.uk    # Where to send mail  
#SBATCH --ntasks=4                       # Run on a single CPU
#SBATCH --mem=70gb                       # Job memory request
#SBATCH --time=05:00:00                  # Time limit hrs:min:sec
#SBATCH --output=basic_job_%j.log        # Standard output and error log
#SBATCH --account=biol-hic-2020          # Project account


#Load module
module load bio/MACS2/2.2.7.1-foss-2019b-Python-3.7.4

#move to directrory and create MACS2 directory
cd /mnt/lustre/groups/biol-hic-2020/jack/processedChipdata/20230818CC_distance_analysis/HCT116_BRD4
mkdir /mnt/lustre/groups/biol-hic-2020/jack/processedChipdata/20230818CC_distance_analysis/HCT116_BRD4/MACS2

#Copy over the input control
cp /mnt/lustre/groups/biol-hic-2020/jack/workingChipdata/HCT116_Brd4/input/SRR2481800_hg38_filtered_sorted.bed input


#Actually running MACS2

macs2 callpeak -t SRR2481799.fastq_sorted_hg38.bam_filtered_sorted.bed \
	-c input/SRR2481800_hg38_filtered_sorted.bed \
	-f BED \
	-g 3.04e+9 \
	-n filtered_BRD4_ChIP \
	--outdir MACS2

cd /mnt/lustre/groups/biol-hic-2020/jack/processedCCdata/20230818CC_distance_analysis