#!/bin/bash
#SBATCH --job-name=filt_SP1_MACS2	 # Job name
#SBATCH --mail-type=END,FAIL             # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=jps558@york.ac.uk    # Where to send mail  
#SBATCH --ntasks=4                       # Run on a single CPU
#SBATCH --mem=70gb                       # Job memory request
#SBATCH --time=05:00:00                  # Time limit hrs:min:sec
#SBATCH --output=basic_job_%j.log        # Standard output and error log
#SBATCH --account=biol-hic-2020          # Project account


#Load module
module load bio/MACS2/2.2.7.1-foss-2019b-Python-3.7.4

#move to directrory and create MACS2 directory
mkdir MACS2
mkdir MACS2/BRD4
mkdir MACS2/SP1


#Actually running MACS2 on BRD4 ChIP

macs2 callpeak -t /mnt/lustre/groups/biol-hic-2020/jack/workingChipdata/HCT116_Brd4/SRR2481799.fastq_sorted_hg38.bam_filtered_sorted.bed \
	-c /mnt/lustre/groups/biol-hic-2020/jack/workingChipdata/HCT116_Brd4/input/SRR2481800_hg38_filtered_sorted.bed \
	-f BED \
	-g hs \
	-p 1e-9 \
	-s 50 \
	--keep-dup auto \
	-n filtered_BRD4_ChIP_p9 \
	--outdir MACS2/BRD4

#Actually running MACS2 on SP1 ChIP
#Re-run if this works- below was never run
#macs2 callpeak -t /mnt/lustre/groups/biol-hic-2020/jack/workingChipdata/HCT116_SP1/ENCFF000PCT_sorted_hg38.bam_filtered_sorted.bed \
	-c /mnt/lustre/groups/biol-hic-2020/jack/workingChipdata/HCT116_SP1/Input/ENCFF000PBY_sorted_hg38.bam_filtered_sorted.bed \
	-f BED \
	-g hs \
	-p 1e-9 \
	-s 50 \
	--keep-dup auto \
	-n filtered_SP1_ChIP_p9 \
	--outdir MACS2/SP1
