#!/usr/bin/env bash
#SBATCH --job-name=GetChIP         # Job name
#SBATCH --partition=nodes               # What partition the job should run on
#SBATCH --time=0-10:00:00               # Time limit (DD-HH:MM:SS)
#SBATCH --ntasks=1                      # Number of MPI tasks to request
#SBATCH --cpus-per-task=1               # Number of CPU cores per MPI task
#SBATCH --mem=10G                        # Total memory to request
#SBATCH --account=biol-cards-2023        # Project account to use
#SBATCH --mail-type=END,FAIL            # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=jps558@york.ac.uk   # Where to send mail
#SBATCH --output=%x-%j.log              # Standard output log
#SBATCH --error=%x-%j.err               # Standard error log

cd /mnt/scratch/users/jps558/Stenning_Data_Analysis/Final_year/2024_25Analysis/EncodeChIP

#Rep 1 and 2 accession map taken from this page https://www.encodeproject.org/experiments/ENCSR463GOT/

mkdir rep1
cd rep1
curl  -L -o ENCFF365BIT.bam https://www.encodeproject.org/files/ENCFF365BIT/@@download/ENCFF365BIT.bam

cd /mnt/scratch/users/jps558/Stenning_Data_Analysis/Final_year/2024_25Analysis/EncodeChIP

mkdir rep2
cd rep2
curl  -L -o ENCFF063JMY.bam https://www.encodeproject.org/files/ENCFF063JMY/@@download/ENCFF063JMY.bam

cd /mnt/scratch/users/jps558/Stenning_Data_Analysis/Final_year/2024_25Analysis/EncodeChIP

#Input accession map taken from https://www.encodeproject.org/experiments/ENCSR517FPJ/

mkdir input
cd input
curl  -L -o ENCFF444JMD.bam https://www.encodeproject.org/files/ENCFF444JMD/@@download/ENCFF444JMD.bam
